# Generated by Django 4.2.2 on 2023-07-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField(null=True)),
                ('date_arrivee', models.DateField(null=True)),
                ('nombre_heures', models.IntegerField(null=True)),
                ('nombre_jours', models.IntegerField(null=True)),
            ],
        ),
    ]
